import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS } from '../theme/colors';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.cardBg,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.lg,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  modalTitle: {
    color: COLORS.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  modalSub: {
    color: COLORS.goldPrimary,
    fontSize: 11,
    fontWeight: '600',
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.cardBgLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeBtnText: {
    color: COLORS.textSecondary,
    fontSize: 16,
    fontWeight: '700',
  },
  shareCardVisual: {
    backgroundColor: COLORS.cardBgLight,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.goldPrimary,
    marginBottom: SPACING.md,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  cardBrand: {
    color: COLORS.textPrimary,
    fontSize: 12,
    fontWeight: '800',
  },
  cardGoldBadge: {
    color: COLORS.goldPrimary,
    fontSize: 10,
    fontWeight: '800',
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: RADIUS.sm,
  },
  cardBody: {
    marginVertical: SPACING.sm,
  },
  cardQuote: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  giftPill: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    padding: SPACING.xs + 2,
    borderRadius: RADIUS.sm,
    marginTop: 8,
  },
  giftText: {
    color: COLORS.emerald,
    fontSize: 11,
    fontWeight: '700',
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.sm,
    paddingTop: SPACING.xs,
    borderTopWidth: 1,
    borderTopColor: COLORS.cardBorderSubtle,
  },
  codeLabel: {
    color: COLORS.textMuted,
    fontSize: 10,
  },
  codeVal: {
    color: COLORS.goldPrimary,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1,
  },
  qrMock: {
    backgroundColor: COLORS.cardBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.cardBorderSubtle,
  },
  qrText: {
    color: COLORS.textSecondary,
    fontSize: 10,
    fontWeight: '700',
  },
  linkContainer: {
    marginBottom: SPACING.md,
  },
  linkLabel: {
    color: COLORS.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 4,
  },
  linkBox: {
    flexDirection: 'row',
    backgroundColor: COLORS.cardBgLight,
    borderRadius: RADIUS.md,
    paddingLeft: SPACING.md,
    paddingRight: 4,
    paddingVertical: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.cardBorderSubtle,
  },
  linkText: {
    color: COLORS.textPrimary,
    fontSize: 11,
    flex: 1,
  },
  copyBtn: {
    backgroundColor: COLORS.goldPrimary,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs + 4,
    borderRadius: RADIUS.sm,
  },
  copyBtnSuccess: {
    backgroundColor: COLORS.emerald,
  },
  copyBtnText: {
    color: '#000',
    fontSize: 12,
    fontWeight: '800',
  },
  shareActions: {
    flexDirection: 'row',
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  shareBtn: {
    flex: 1,
    paddingVertical: SPACING.md - 2,
    borderRadius: RADIUS.md,
    alignItems: 'center',
  },
  shareBtnText: {
    color: '#FFF',
    fontWeight: '800',
    fontSize: 13,
  },
  closeFullBtn: {
    backgroundColor: COLORS.cardBgLight,
    paddingVertical: SPACING.md - 2,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.cardBorderSubtle,
  },
  closeFullText: {
    color: COLORS.textSecondary,
    fontWeight: '700',
  },
});
